# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNPyQ3rwogyv5y21kPFd0nsPs4JJsozl
"""

ip1=int(input("enter first input"))
ip2=int(input("enter second input"))
result=ip1+ip2
print(result)

